In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn.preprocessing import StandardScaler

In [57]:
df=pd.read_csv('mushrooms.csv')
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [61]:
df.tail()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[5 rows x 23 columns]

In [62]:
num_val={'e':1,'p':0}
df['class']=df["class"].apply(lambda x:num_val[x])
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0      0         x           s         n       t    p               f   
1      1         x           s         y       t    a               f   
2      1         b           s         w       t    l               f   
3      0         x           y         w       t    p               f   
4      1         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [64]:
df=pd.get_dummies(df)
df1.head()

class  cap-shape_b  cap-shape_f  cap-shape_s  cap-shape_x  cap-surface_f  \
0      0            0            0            0            1              0   
1      1            0            0            0            1              0   
2      1            1            0            0            0              0   
3      0            0            0            0            1              0   
4      1            0            0            0            1              0   

   cap-surface_s  cap-surface_y  cap-color_e  cap-color_g  ...  population_a  \
0              1              0            0            0  ...             0   
1              1              0            0            0  ...             0   
2              1              0            0            0  ...             0   
3              0              1            0            0  ...             0   
4              1              0            0            1  ...             1   

   population_n  population_s  population_v  population_y  habitat_d  \
0             0             1             0             0          0   
1             1             0             0             0          0   
2             1             0             0             0          0   
3             0             1             0             0          0   
4             0             0             0             0          0   

   habitat_g  habitat_m  habitat_p  habitat_u  
0          0          0          0          1  
1          1          0          0          0  
2          0          1          0          0  
3          0          0          0          1  
4          1          0          0          0  

[5 rows x 66 columns]

In [65]:
df.describe()

class  cap-shape_b  cap-shape_f  cap-shape_s  cap-shape_x  \
count  1000.0000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.8980     0.221000     0.215000     0.031000     0.533000   
std       0.3028     0.415128     0.411028     0.173404     0.499159   
min       0.0000     0.000000     0.000000     0.000000     0.000000   
25%       1.0000     0.000000     0.000000     0.000000     0.000000   
50%       1.0000     0.000000     0.000000     0.000000     1.000000   
75%       1.0000     0.000000     0.000000     0.000000     1.000000   
max       1.0000     1.000000     1.000000     1.000000     1.000000   

       cap-surface_f  cap-surface_s  cap-surface_y  cap-color_e  cap-color_g  \
count     1000.00000     1000.00000    1000.000000  1000.000000  1000.000000   
mean         0.20800        0.36600       0.426000     0.001000     0.094000   
std          0.40608        0.48195       0.494741     0.031623     0.291975   
min          0.00000        0.00000       0.000000     0.000000     0.000000   
25%          0.00000        0.00000       0.000000     0.000000     0.000000   
50%          0.00000        0.00000       0.000000     0.000000     0.000000   
75%          0.00000        1.00000       1.000000     0.000000     0.000000   
max          1.00000        1.00000       1.000000     1.000000     1.000000   

       ...  population_a  population_n  population_s  population_v  \
count  ...   1000.000000   1000.000000   1000.000000   1000.000000   
mean   ...      0.062000      0.213000      0.410000      0.182000   
std    ...      0.241276      0.409633      0.492079      0.386038   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      1.000000      0.000000   
max    ...      1.000000      1.000000      1.000000      1.000000   

       population_y   habitat_d    habitat_g    habitat_m    habitat_p  \
count   1000.000000  1000.00000  1000.000000  1000.000000  1000.000000   
mean       0.133000     0.10000     0.462000     0.221000     0.078000   
std        0.339745     0.30015     0.498803     0.415128     0.268306   
min        0.000000     0.00000     0.000000     0.000000     0.000000   
25%        0.000000     0.00000     0.000000     0.000000     0.000000   
50%        0.000000     0.00000     0.000000     0.000000     0.000000   
75%        0.000000     0.00000     1.000000     0.000000     0.000000   
max        1.000000     1.00000     1.000000     1.000000     1.000000   

        habitat_u  
count  1000.00000  
mean      0.13900  
std       0.34612  
min       0.00000  
25%       0.00000  
50%       0.00000  
75%       0.00000  
max       1.00000  

[8 rows x 66 columns]

In [66]:
x=df.iloc[:,1:]
x.head()

cap-shape_b  cap-shape_f  cap-shape_s  cap-shape_x  cap-surface_f  \
0            0            0            0            1              0   
1            0            0            0            1              0   
2            1            0            0            0              0   
3            0            0            0            1              0   
4            0            0            0            1              0   

   cap-surface_s  cap-surface_y  cap-color_e  cap-color_g  cap-color_n  ...  \
0              1              0            0            0            1  ...   
1              1              0            0            0            0  ...   
2              1              0            0            0            0  ...   
3              0              1            0            0            0  ...   
4              1              0            0            1            0  ...   

   population_a  population_n  population_s  population_v  population_y  \
0             0             0             1             0             0   
1             0             1             0             0             0   
2             0             1             0             0             0   
3             0             0             1             0             0   
4             1             0             0             0             0   

   habitat_d  habitat_g  habitat_m  habitat_p  habitat_u  
0          0          0          0          0          1  
1          0          1          0          0          0  
2          0          0          1          0          0  
3          0          0          0          0          1  
4          0          1          0          0          0  

[5 rows x 65 columns]

In [67]:
y=df.iloc[:,0]
y.head()

0    0
1    1
2    1
3    0
4    1
Name: class, dtype: int64

In [68]:
x.shape

(1000, 65)

In [69]:
y.shape

(1000,)

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

In [71]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [72]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

1.0
[[ 22   0]
 [  0 198]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00       198

    accuracy                           1.00       220
   macro avg       1.00      1.00      1.00       220
weighted avg       1.00      1.00      1.00       220



In [73]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

1.0
[[ 22   0]
 [  0 198]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00       198

    accuracy                           1.00       220
   macro avg       1.00      1.00      1.00       220
weighted avg       1.00      1.00      1.00       220



In [74]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

1.0
[[ 22   0]
 [  0 198]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00       198

    accuracy                           1.00       220
   macro avg       1.00      1.00      1.00       220
weighted avg       1.00      1.00      1.00       220

